AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  deploy lambda
Globals:
  Function:
    Timeout: 3
  Api:
    OpenApiVersion: 3.0.1

Parameters:
  stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  ApiDeploy:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref stage
#      OpenApiVersion: '2.0'
      Auth:
        ApiKeyRequired: true

  ProducerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub
        - '${Stack_Name}-producer-runner'
        - Stack_Name: !Ref "AWS::StackName"
      Description: "this lambda runs '${Stack_Name}' producers"
      Environment:
        Variables:
          test: !Sub '{{resolve:ssm:/test/${stage}}}'
      CodeUri: lambda_functions/
      Handler: producer.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiDeploy
            Path: /aggregations
            Method: POST
